version: "3.8"

services:
    api:
        build: ./
        ports:
            - "8080:8080"
        environment:
            - DB_URL=mongodb://localhost:27017/sibtain
        depends_on:
            - db
        volumes:
            - ./:/App
        network_mode: host

    db:
        image: mongo
        ports:
            - "27017:27017"
        network_mode: host
        volumes:
            - comments:/data/db
volumes:
    comments: