from uuid import uuid4
from pydantic import BaseModel, Field


class OutputTemplate(BaseModel):
    """
    Pydantic models for Serializing Output Result generated by Pipeline

    """
    id: str = Field(default_factory=uuid4, alias="_id")
    category: str = Field(...)
    entities: dict = Field(...)
    comment: str = Field(...)

    class Config:
        allow_population_by_field_name = True
        schema_extra = {
            "example": {
                "id": "00010203-0405-0607-0809-0a0b0c0d0e0f",
                "category": "Technology",
                "entities": {'Name': ['Sibtain', 'Raza']},
                "comment": "comment on technology"
            }
        }
